### ISSUE TITLE
Неверная сумма транзакции в базе данных SQL

### ISSUE THREAD

**Issue by Mari14460** [Mari14460/Diploma-Project#4]
**Описание:** Неверная сумма транзакции в базе данных SQL в таблице payment_entity в столбце amount
**Предусловия:** Запустить приложение как описано в [README.md](https://github.com/Mari14460/Diploma-Project/blob/main/README.md)
**Шаги воспроизведения:**

1. Открыть приложение по адресу http://localhost:8080/
2. Нажать на кнопку "Купить"
3. Номер карты "4444 4444 4444 4441"
4. Месяц "09"
5. Год "24"
6. Владелец "Владимир Ленин"
7. CVC "123"
8. Нажать на кнопку "Продолжить"
9. Проверить с помощью DBeaver таблицу payment_entity столбец amount

**Фактический результат:** 4,500,000
**Ожидаемый результат:** 45,000

**Скриншот:**
<img width="1677" alt="Снимок экрана 2023-01-31 в 21 04 26" src="https://user-images.githubusercontent.com/112805255/215938693-c8f162e9-d3fa-45f7-881b-2776623543c6.png">

**Окружение:**
* macOS 12.6 (21G115)
* IntelliJ IDEA 2022.2.3 (Community Edition)
* Java version 11.0.16.1
* Google Chrome Версия 109.0.5414.87 (Официальная сборка), (arm64)

**Comment by ArRomanov** [comment]
На самом деле, в БД сумма записывается в копейках, чтобы избежать ошибок при округлении. Поэтому данный баг можно закрыть

**Comment by Mari14460** [comment]
Уточнили у PO что это правильное значение в копейках. Закрываем баг.
